baseURL: 'https://ritaxu.github.io/'
languageCode: 'en-us'
title: 'HOME'
theme: 'hugo-PaperMod'

enableInlineShortcodes: true #允许内联短码
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true

languages:
    en:
      //languageName: "English"
      # contentDir: content/english
      weight: 1
      profileMode:
        enabled: true
        title: (〃'▽'〃)
        subtitle: Ruotong Universe